# Generated by Django 5.1.11 on 2025-06-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pronounce_advanced",
            "0004_alter_dailypractice_user_alter_dailysubmission_user_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, unique=True)),
                ("image", models.ImageField(blank=True, upload_to="pronounce_images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
